<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://web.company.epam.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://api.company.epam.com/" name="CompanyWebServiceImplService" targetNamespace="http://web.company.epam.com/">
    <wsdl:import location="types.wsdl" namespace="http://api.company.epam.com/"></wsdl:import>
    <wsdl:binding name="CompanyWebServiceImplServiceSoapBinding" type="ns1:CompanyService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="createCompany">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="createCompany">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="createCompanyResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CompanyWebServiceImplService">
        <wsdl:port binding="tns:CompanyWebServiceImplServiceSoapBinding" name="CompanyWebServiceImplPort">
            <soap:address location="http://localhost:8080/CompanyWebService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>